ksamp: 
	gcc ksamp.c -o ksamp

help:
	#Ayuda
	./ksamp.o -h

	./ksamp.o --help

	#Parte C
	./ksamp.o -s

	./ksamp.o --parteC

	#Parte D
	./ksamp.o -l 2 10

	./ksamp.o --parteD 1 5

	#Comandos invalidos

	./ksamp.o -a

	./ksamp.o -s 2

	./ksamp.o -l 1

	./ksamp.o -l 10 5
	
	./ksamp.o -s -l

